"""
This is a setup.py script generated by py2applet

Usage:
    python3 build-files/setup-py2app.py py2app
"""

from setuptools import setup

APP = ['HomeBankCSV.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'build-files/images/icon.icns'}

setup(
    author="Caspar Verhey",
    author_email="caspar@verhey.net",
    license="MIT",
    url="https://github.com/cwverhey/HomeBankCSV",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
